= README
:experimental:
:icons: font
:revdate: 2023-08-09
:sectnums:
:sectnumlevels: 5
:toclevels: 5
:toc:

:blank: pass:[ +]

== Build
=== Build Java program distribution
[source,cmd]
----
mvn clean verify
----

This will generate two distribution archives:

. `target/pdf-tools-0.1.0-windows.zip`
. `target/pdf-tools-0.1.0-linux.zip`


=== Build Docker image
==== Prerequisites
. Install https://docs.docker.com/[Docker].

. Start Docker Engine.
+
[source,cmd]
----
sudo service docker start
----

==== Build
. Run Maven build.
+
[source,cmd]
----
mvn -Pdocker verify
----


== Installation
=== Using Java program distribution
==== Windows
Unzip `target/pdf-tools-0.1.0-windows.zip`.

==== Linux
[source,sh]
----
unzip target/pdf-tools-0.1.0-linux.zip

chmod u+x pdf-tools-0.1.0/bin/pdf-tools.sh
----


== Software Bill of Materials (SBOM)
See generated artifact `+pdf-tools-${VERSION}-cyclonedx.json+`


== Usage
=== Using Java program
==== Encrypt PDF document
[discrete]
===== Linux
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    EncryptPdf \#<1>
    "/tmp/kay.pdf" "/tmp/encrypted-kay.pdf"#<2>
----
<1> Command name
<2> Command arguments - input PDF file, output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    EncryptPdf^#<1>
    "%TEMP%\kay.pdf" "%TEMP%\encrypted-kay.pdf"#<2>
----
<1> Command name
<2> Command arguments - input PDF file, output PDF file

==== Decrypt PDF documents
[discrete]
===== Linux
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    DecryptPdfs \#<1>
    "/tmp/encrypyed-pdfs-dir" "/tmp/decrypyed-pdfs-dir"#<2>
----
<1> Command name
<2> Command arguments - input (encrypted) PDFs directory, output (decrypted) PDFs directory

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    DecryptPdfs^#<1>
    "%TEMP%\encrypyed-pdfs-dir" "%TEMP%\decrypyed-pdfs-dir"#<2>
----
<1> Command name
<2> Command arguments - input (encrypted) PDFs directory, output (decrypted) PDFs directory

==== Convert PDF pages to images
[discrete]
===== Linux
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    PdfToImage \#<1>
    "/tmp/input.pdf" "/tmp/" "1,2,3" 300 "jpeg" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    PdfToImage^#<1>
    "%TEMP%\input.pdf" "%TEMP%" "1,2,3" 300 "jpeg" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

==== Remove pages from PDF document
[discrete]
===== Linux
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    RemovePages \#<1>
    "/tmp/input.pdf" "1,3" "/tmp/output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, page numbers to remove, output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    RemovePages^#<1>
    "%TEMP%\input.pdf" "1,3" "%TEMP%\output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, page numbers to remove, output PDF file

==== Add watermark to PDF pages
[discrete]
===== Linux
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    AddWatermark \#<1>
    "/tmp/input.pdf" "DUPLICATE" 40 "/tmp/output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, watermark text, font size, output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    AddWatermark^#<1>
    "%TEMP%\input.pdf" "DUPLICATE" 40 "%TEMP%\output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, watermark text, font size, output PDF file

==== Convert PDF document to grayscale
[discrete]
===== Linux
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    ConvertToGrayscale \#<1>
    "/tmp/input.pdf" 200 "LEGAL" "/tmp/output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, image DPI, output page size, output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    ConvertToGrayscale^#<1>
    "%TEMP%\input.pdf" 200 "LEGAL" "%TEMP%\output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, image DPI, output page size, output PDF file

==== Create PDF document from images
[discrete]
===== Linux
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    ImagesToPdf \#<1>
    "/tmp/images/" "A4" "top-left" "standard" "/tmp/output.pdf"#<2>
----
<1> Command name
<2> Command arguments - input images directory, output page size, image position, page margins, output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    ImagesToPdf^#<1>
    "%TEMP%\images" "A4" "top-left" "standard" "%TEMP%\output.pdf"#<2>
----
<1> Command name
<2> Command arguments - input images directory, output page size, image position, page margins, output PDF file

==== Run a transformation pipeline
[discrete]
===== Windows
Create a pipeline specification file.

.C:\Users\foo\AppData\Local\Temp\pdf-transformation-pipeline.yaml
[source,yaml]
----
transformations:
  - type: ImagesToPdf
    args:
      input-images-directory: 'C:\Users\foo\AppData\Local\Temp\images'
      output-page-size: 'A4'
      image-position: 'top-left'
      page-margins: 'standard'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'

  - type: RemovePages
    args:
      input-pdf-file: 'C:\Users\foo\AppData\Local\Temp\input.pdf'
      pages-to-remove: '1,3'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'

  - type: ConvertToGrayscale
    args:
      input-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'
      dpi: '200.0'
      output-page-size: 'LEGAL'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'

  - type: AddWatermark
    args:
      input-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'
      watermark-text : 'DUPLICATE'
      watermark-font-size: '40'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'

  - type: EncryptPdf
    args:
      input-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\encrypted\output.pdf'

  - type: DecryptPdfs
    args:
      input-pdfs-directory: 'C:\Users\foo\AppData\Local\Temp\encrypted'
      output-pdfs-directory: 'C:\Users\foo\AppData\Local\Temp\decrypted'
----

Run the pipeline.

[source,cmd]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    Pipeline^#<1>
    "C:\Users\foo\AppData\Local\Temp\pdf-transformation-pipeline.yaml"#<2>
----
<1> Command name
<2> Command arguments - pipeline specification file

[discrete]
===== Linux
[source,sh]
----
cat <<EOF > /tmp/pdf-transformation-pipeline.yaml
transformations:
  - type: ImagesToPdf
    args:
      input-images-directory: '/tmp/images'
      output-page-size: 'A4'
      image-position: 'top-left'
      page-margins: 'standard'
      output-pdf-file: '/tmp/intermediate.pdf'

  - type: RemovePages
    args:
      input-pdf-file: '/tmp/input.pdf'
      pages-to-remove: '1,3'
      output-pdf-file: '/tmp/intermediate.pdf'

  - type: ConvertToGrayscale
    args:
      input-pdf-file: '/tmp/intermediate.pdf'
      dpi: '200.0'
      output-page-size: 'LEGAL'
      output-pdf-file: '/tmp/intermediate.pdf'

  - type: AddWatermark
    args:
      input-pdf-file: '/tmp/intermediate.pdf'
      watermark-text : 'DUPLICATE'
      watermark-font-size: '40'
      output-pdf-file: '/tmp/intermediate.pdf'

  - type: EncryptPdf
    args:
      input-pdf-file: '/tmp/intermediate.pdf'
      output-pdf-file: '/tmp/encrypted/output.pdf'

  - type: DecryptPdfs
    args:
      input-pdfs-directory: '/tmp/encrypted'
      output-pdfs-directory: '/tmp/decrypted'

EOF

pdf-tools-0.1.0/bin/pdf-tools.sh \
    Pipeline \#<1>
    "/tmp/pdf-transformation-pipeline.yaml"#<2>
----
<1> Command name
<2> Command arguments - pipeline specification file


=== Using Docker container
==== Encrypt PDF document
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    EncryptPdf \#<2>
    "/tmp/bar/kay.pdf" "/tmp/bar/encrypted-kay.pdf"#<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, output PDF file

==== Decrypt PDF documents
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    DecryptPdfs \#<2>
    "/tmp/bar/encrypyed-pdfs" "/tmp/bar/decrypyed-pdfs"#<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input (encrypted) PDFs directory, output (decrypted) PDFs directory

==== Convert PDF pages to images
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    PdfToImage \#<2>
    "/tmp/bar/input.pdf" "/tmp/bar/" "1,2,3" 300 "jpeg" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

==== Remove pages from PDF document
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    RemovePages \#<2>
    "/tmp/bar/input.pdf" "1,3" "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, page numbers to remove, output PDF file

==== Add watermark to PDF pages
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    AddWatermark \#<2>
    "/tmp/bar/input.pdf" "DUPLICATE" 40 "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, watermark text, font size, output PDF file

==== Convert PDF document to grayscale
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    ConvertToGrayscale \#<2>
    "/tmp/bar/input.pdf" 200 "LEGAL" "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, image DPI, output page size, output PDF file

==== Create PDF document from images
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    ImagesToPdf \#<2>
    "/tmp/bar/images/" "A4" "top-left" "standard" "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input images directory, output page size, image position, page margins, output PDF file

==== Run a transformation pipeline
[source,sh]
----
cat <<EOF > /tmp/foo/pdf-transformation-pipeline.yaml
transformations:
  - type: ImagesToPdf
    args:
      input-images-directory: '/tmp/bar/images'
      output-page-size: 'A4'
      image-position: 'top-left'
      page-margins: 'standard'
      output-pdf-file: '/tmp/bar/intermediate.pdf'

  - type: RemovePages
    args:
      input-pdf-file: '/tmp/bar/input.pdf'
      pages-to-remove: '1,3'
      output-pdf-file: '/tmp/bar/intermediate.pdf'

  - type: ConvertToGrayscale
    args:
      input-pdf-file: '/tmp/bar/intermediate.pdf'
      dpi: '200.0'
      output-page-size: 'LEGAL'
      output-pdf-file: '/tmp/bar/intermediate.pdf'

  - type: AddWatermark
    args:
      input-pdf-file: '/tmp/bar/intermediate.pdf'
      watermark-text : 'DUPLICATE'
      watermark-font-size: '40'
      output-pdf-file: '/tmp/bar/intermediate.pdf'

  - type: EncryptPdf
    args:
      input-pdf-file: '/tmp/bar/intermediate.pdf'
      output-pdf-file: '/tmp/bar/output.pdf'

  - type: DecryptPdfs
    args:
      input-pdfs-directory: '/tmp/bar'
      output-pdfs-directory: '/tmp/baz'

EOF

docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    Pipeline \#<2>
    "/tmp/bar/pdf-transformation-pipeline.yaml"#<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - pipeline specification file
