= README
:experimental:
:icons: font
:revdate: 2023-05-20
:sectnums:
:sectnumlevels: 5
:toclevels: 5
:toc:

:blank: pass:[ +]

////
== Development
=== GraalVM native image
==== Native image configuration
. The procedure to generate native image configuration using native image agent is as follows:
  .. Run the following command:
+
--
[source,sh]
----
mvn \
    -Pnative \
    -Dagent=true \#<1>
    -DskipNativeTests \#<2>
    clean test \
    native:metadata-copy #<3>
----
<1> Run tests with the native image agent enabled, to generate native configuration files.
<2> Skip running native tests because running them with the native image agent enabled results into errors.
<3> Copy generated native image configuration files to an appropriate location.
--
  .. Manually review the changes in files in `src/main/resources/META-INF/native-image` directory.

  .. Make appropriate changes to `src/graalvm-native-image-config/access-filter.json` file.

  .. Remove unwanted resources from `src/main/resources/META-INF/native-image/serialization-config.json` file.
+
NOTE: Until https://github.com/oracle/graal/issues/2602[#2602 - Native image agent filter: exclude resources] is resolved, we need to manually delete unwanted resources (such as the resources related to testing framework) from the `META-INF/native-image/resource-config.json` generated by the native image agent.

. Until https://github.com/oracle/graal/issues/2922[#2922 - Native image/Tracing agent filter: Improve syntax] is resolved, we won't be able to use `{ "excludeClasses": "rahulb.pdftools.**.*Test" }` in `src/graalvm-native-image-config/access-filter.json`.

==== IDE
. Use GraalVM as the SDK for IntelliJ IDEA project.
////


== Build
=== Build Java archive (JAR)
[source,cmd]
----
mvn clean verify
----

////
=== Build Windows executable
==== Prerequisites
. Install https://www.graalvm.org/[GraalVM] v22.3+.

. Install https://www.graalvm.org/22.3/reference-manual/native-image/[Native Image].
+
NOTE: On Windows, Native Image requires Visual Studio Code and Microsoft Visual C++(MSVC).

. Install https://maven.apache.org/[Apache Maven]

==== Build
. Open `Developer Command Prompt for VS 2022` in Windows Terminal.
+
.Developer Command Prompt for VS 2022
[source]
----
******************************************************
** Visual Studio 2022 Developer Command Prompt v17.5.3
** Copyright (c) 2022 Microsoft Corporation
******************************************************

>
----

. Run Maven build.
+
[source,cmd]
----
> cd <project-directory>

pdf-tools> set JAVA_HOME=<graalvm-home-directory>

pdf-tools> mvn -Pnative package
----
////


=== Build Docker image
==== Prerequisites
. Install https://docs.docker.com/[Docker].

. Start Docker Engine.
+
[source,cmd]
----
sudo service docker start
----

==== Build
. Run Maven build.
+
[source,cmd]
----
mvn -Pdocker verify
----


== Usage
=== Using Windows program
==== Encrypt PDF document
[source,cmd]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    EncryptPdf^#<1>
    "%TEMP%\kay.pdf" "%TEMP%\encrypted-kay.pdf"#<2>
----
<1> Command name
<2> Command arguments - input PDF file, output PDF file

==== Convert PDF pages to images
[source,sh]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    PdfToImage^#<1>
    "%TEMP%\input.pdf" "%TEMP%" "1,2,3" 300 "jpeg" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

==== Remove pages from PDF document
[source,sh]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    RemovePages^#<1>
    "%TEMP%\input.pdf" "1,3" "%TEMP%\output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, page numbers to remove, output PDF file

==== Add watermark to PDF pages
[source,sh]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    AddWatermark^#<1>
    "%TEMP%\input.pdf" "DUPLICATE" 40 "%TEMP%\output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, watermark text, font size, output PDF file

==== Convert PDF document to grayscale
[source,sh]
----
pdf-tools-0.1.0\bin\pdf-tools.bat^
    ConvertToGrayscale^#<1>
    "%TEMP%\input.pdf" 200 "LEGAL" "%TEMP%\output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, image DPI, output page size, output PDF file


=== Using Java program on Linux
==== Encrypt PDF document
[source,cmd]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    EncryptPdf \#<1>
    "/tmp/kay.pdf" "/tmp/encrypted-kay.pdf"#<2>
----
<1> Command name
<2> Command arguments - input PDF file, output PDF file

==== Convert PDF pages to images
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    PdfToImage \#<1>
    "/tmp/input.pdf" "/tmp/" "1,2,3" 300 "jpeg" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

==== Remove pages from PDF document
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    RemovePages \#<1>
    "/tmp/input.pdf" "1,3" "/tmp/output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, page numbers to remove, output PDF file

==== Add watermark to PDF pages
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    AddWatermark \#<1>
    "/tmp/input.pdf" "DUPLICATE" 40 "/tmp/output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, watermark text, font size, output PDF file

==== Convert PDF document to grayscale
[source,sh]
----
pdf-tools-0.1.0/bin/pdf-tools.sh \
    ConvertToGrayscale \#<1>
    "/tmp/input.pdf" 200 "LEGAL" "/tmp/output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, image DPI, output page size, output PDF file


=== Using Docker container
==== Encrypt PDF document
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    EncryptPdf \#<2>
    "/tmp/bar/kay.pdf" "/tmp/bar/encrypted-kay.pdf"#<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, output PDF file

==== Convert PDF pages to images
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    PdfToImage \#<2>
    "/tmp/bar/input.pdf" "/tmp/bar/" "1,2,3" 300 "jpeg" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

==== Remove pages from PDF document
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    RemovePages \#<2>
    "/tmp/bar/input.pdf" "1,3" "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, page numbers to remove, output PDF file

==== Add watermark to PDF pages
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    AddWatermark \#<2>
    "/tmp/bar/input.pdf" "DUPLICATE" 40 "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, watermark text, font size, output PDF file

==== Convert PDF document to grayscale
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    ConvertToGrayscale \#<2>
    "/tmp/bar/input.pdf" 200 "LEGAL" "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, image DPI, output page size, output PDF file


////
=== Using Windows executable
==== Encrypt PDF document
[source,cmd]
----
pdf-tools.exe ^
    EncryptPdf ^#<1>
    "%TEMP%/foo/kay.pdf" "%TEMP%/foo/encrypted-kay.pdf"#<2>
----
<1> Command name
<2> Command arguments - input PDF file, output PDF file

==== Convert PDF pages to images
[source,cmd]
----
pdf-tools.exe ^
    PdfToImage ^#<1>
    "%TEMP%/foo/input.pdf" "%TEMP%/foo/" "1,2,3" 300 "jpeg" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

==== Remove pages from PDF document
[source,cmd]
----
pdf-tools.exe ^
    RemovePages ^#<1>
    "%TEMP%/foo/input.pdf" "1,3" "%TEMP%/foo/output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, page numbers to remove, output PDF file

==== Add watermark to PDF pages
[source,cmd]
----
pdf-tools.exe ^
    AddWatermark ^#<1>
    "%TEMP%/foo/input.pdf" "DUPLICATE" 40 "%TEMP%/foo/output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, watermark text, font size, output PDF file

==== Convert PDF document to grayscale
[source,cmd]
----
pdf-tools.exe ^
    ConvertToGrayscale ^#<1>
    "%TEMP%/foo/input.pdf" 200 "LEGAL" "%TEMP%/foo/output.pdf" #<2>
----
<1> Command name
<2> Command arguments - input PDF file, image DPI, output page size, output PDF file
////
