= pdf-tools
:experimental:
:icons: font
:revdate: 2023-08-25
:sectnums:
:sectnumlevels: 5
:toclevels: 5
:toc:

:blank: pass:[ +]
:hide-docker:

`pdf-tools` is a command-line application capable of doing the following things:

. <<readme-usage-encrypt-pdf-doc>>
. <<readme-usage-decrypt-pdf-docs>>
. <<readme-usage-convert-pdf-to-images>>
. <<readme-usage-remove-pdf-pages>>
. <<readme-usage-add-watermark-to-pdf>>
. <<readme-usage-convert-pdf-to-grayscale>>
. <<readme-usage-create-pdf-from-images>>
. <<readme-usage-run-transformation-pipeline>>


== Software Bill of Materials (SBOM)
See release asset `+pdf-tools-${RELEASE_VERSION}-sbom-cyclonedx.json+`.


== Installation
=== Using Java program distribution
[discrete]
==== Windows
Download and unzip `+pdf-tools-%RELEASE_VERSION%-windows.zip+` from release assets.

[discrete]
==== Linux
Download `+pdf-tools-${RELEASE_VERSION}-linux.zip+` from release assets.

Then, do the following:

[source,sh]
----
unzip target/pdf-tools-${RELEASE_VERSION}-linux.zip

chmod u+x pdf-tools-${RELEASE_VERSION}/bin/pdf-tools.sh
----


== Usage
[#readme-usage-encrypt-pdf-doc]
=== Encrypt (add password protection) a PDF document
[discrete]
==== Using Java program
[discrete]
===== Linux
[source,sh]
----
pdf-tools-${RELEASE_VERSION}/bin/pdf-tools.sh EncryptPdf \
    "/tmp/kay.pdf" "/tmp/encrypted-kay.pdf"
----

where,

* `/tmp/kay.pdf` is the input PDF file
* `/tmp/encrypted-kay.pdf` is the output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-%RELEASE_VERSION%\bin\pdf-tools.bat EncryptPdf^
    "%TEMP%\kay.pdf" "%TEMP%\encrypted-kay.pdf"
----

where,

* `%TEMP%\kay.pdf` is the input PDF file
* `%TEMP%\encrypted-kay.pdf` is the output PDF file


ifndef::hide-docker[]
[discrete]
==== Using Docker container
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools EncryptPdf \
    "/tmp/bar/kay.pdf" "/tmp/bar/encrypted-kay.pdf"
----

where,

* `/tmp/bar/kay.pdf` is the input PDF file
* `/tmp/bar/encrypted-kay.pdf` is the output PDF file

endif::[]

[#readme-usage-decrypt-pdf-docs]
=== Decrypt (remove password protection) PDF documents
[discrete]
==== Using Java program
[discrete]
===== Linux
[source,sh]
----
pdf-tools-${RELEASE_VERSION}/bin/pdf-tools.sh DecryptPdfs \
    "/tmp/encrypyed-pdfs-dir" "/tmp/decrypyed-pdfs-dir"#<1>
----
<1> Command arguments - input (encrypted) PDFs directory, output (decrypted) PDFs directory

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-%RELEASE_VERSION%\bin\pdf-tools.bat DecryptPdfs^
    "%TEMP%\encrypyed-pdfs-dir" "%TEMP%\decrypyed-pdfs-dir"#<1>
----
<1> Command arguments - input (encrypted) PDFs directory, output (decrypted) PDFs directory

ifndef::hide-docker[]
[discrete]
==== Using Docker container
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools DecryptPdfs \
    "/tmp/bar/encrypyed-pdfs" "/tmp/bar/decrypyed-pdfs"#<1>
----
<1> Command arguments - input (encrypted) PDFs directory, output (decrypted) PDFs directory
endif::[]

[#readme-usage-convert-pdf-to-images]
=== Convert PDF pages to images
[discrete]
==== Using Java program
[discrete]
===== Linux
[source,sh]
----
pdf-tools-${RELEASE_VERSION}/bin/pdf-tools.sh PdfToImage \
    "/tmp/input.pdf" "/tmp/" "1,2,3" 300 "jpeg" #<1>
----
<1> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-%RELEASE_VERSION%\bin\pdf-tools.bat PdfToImage^
    "%TEMP%\input.pdf" "%TEMP%" "1,2,3" 300 "jpeg" #<1>
----
<1> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

ifndef::hide-docker[]
[discrete]
==== Using Docker container
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools PdfToImage \
    "/tmp/bar/input.pdf" "/tmp/bar/" "1,2,3" 300 "jpeg" #<1>
----
<1> Command arguments - input PDF file, output directory, page numbers, DPI, image format.
endif::[]

[#readme-usage-remove-pdf-pages]
=== Remove pages from a PDF document
[discrete]
==== Using Java program
[discrete]
===== Linux
[source,sh]
----
pdf-tools-${RELEASE_VERSION}/bin/pdf-tools.sh RemovePages \
    "/tmp/input.pdf" "1,3" "/tmp/output.pdf" #<1>
----
<1> Command arguments - input PDF file, page numbers to remove, output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-%RELEASE_VERSION%\bin\pdf-tools.bat RemovePages^
    "%TEMP%\input.pdf" "1,3" "%TEMP%\output.pdf" #<1>
----
<1> Command arguments - input PDF file, page numbers to remove, output PDF file

ifndef::hide-docker[]
[discrete]
==== Using Docker container
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools RemovePages \
    "/tmp/bar/input.pdf" "1,3" "/tmp/bar/output.pdf" #<1>
----
<1> Command arguments - input PDF file, page numbers to remove, output PDF file
endif::[]

[#readme-usage-add-watermark-to-pdf]
=== Add a watermark to PDF pages
[discrete]
==== Using Java program
[discrete]
===== Linux
[source,sh]
----
pdf-tools-${RELEASE_VERSION}/bin/pdf-tools.sh AddWatermark \
    "/tmp/input.pdf" "DUPLICATE" 40 "/tmp/output.pdf" #<1>
----
<1> Command arguments - input PDF file, watermark text, font size, output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-%RELEASE_VERSION%\bin\pdf-tools.bat AddWatermark^
    "%TEMP%\input.pdf" "DUPLICATE" 40 "%TEMP%\output.pdf" #<1>
----
<1> Command arguments - input PDF file, watermark text, font size, output PDF file

ifndef::hide-docker[]
[discrete]
==== Using Docker container
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools AddWatermark \
    "/tmp/bar/input.pdf" "DUPLICATE" 40 "/tmp/bar/output.pdf" #<1>
----
<1> Command arguments - input PDF file, watermark text, font size, output PDF file
endif::[]

[#readme-usage-convert-pdf-to-grayscale]
=== Convert a colored PDF document to grayscale
[discrete]
==== Using Java program
[discrete]
===== Linux
[source,sh]
----
pdf-tools-${RELEASE_VERSION}/bin/pdf-tools.sh ConvertToGrayscale \
    "/tmp/input.pdf" 200 "LEGAL" "/tmp/output.pdf" #<1>
----
<1> Command arguments - input PDF file, image DPI, output page size, output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-%RELEASE_VERSION%\bin\pdf-tools.bat ConvertToGrayscale^
    "%TEMP%\input.pdf" 200 "LEGAL" "%TEMP%\output.pdf" #<1>
----
<1> Command arguments - input PDF file, image DPI, output page size, output PDF file

ifndef::hide-docker[]
[discrete]
==== Using Docker container
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools ConvertToGrayscale \
    "/tmp/bar/input.pdf" 200 "LEGAL" "/tmp/bar/output.pdf" #<1>
----
<1> Command arguments - input PDF file, image DPI, output page size, output PDF file
endif::[]

[#readme-usage-create-pdf-from-images]
=== Create a PDF document from images
[discrete]
==== Using Java program
[discrete]
===== Linux
[source,sh]
----
pdf-tools-${RELEASE_VERSION}/bin/pdf-tools.sh ImagesToPdf \
    "/tmp/images/" "A4" "top-left" "standard" "/tmp/output.pdf"#<1>
----
<1> Command arguments - input images directory, output page size, image position, page margins, output PDF file

[discrete]
===== Windows
[source,cmd]
----
pdf-tools-%RELEASE_VERSION%\bin\pdf-tools.bat ImagesToPdf^
    "%TEMP%\images" "A4" "top-left" "standard" "%TEMP%\output.pdf"#<1>
----
<1> Command arguments - input images directory, output page size, image position, page margins, output PDF file

ifndef::hide-docker[]
[discrete]
==== Using Docker container
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools ImagesToPdf \
    "/tmp/bar/images/" "A4" "top-left" "standard" "/tmp/bar/output.pdf" #<1>
----
<1> Command arguments - input images directory, output page size, image position, page margins, output PDF file
endif::[]

[#readme-usage-run-transformation-pipeline]
=== Run a PDF transformation pipeline
[discrete]
==== Using Java program
[discrete]
===== Windows
Create a pipeline specification file.

.C:\Users\foo\AppData\Local\Temp\pdf-transformation-pipeline.yaml
[source,yaml]
----
transformations:
  - type: ImagesToPdf
    args:
      input-images-directory: 'C:\Users\foo\AppData\Local\Temp\images'
      output-page-size: 'A4'
      image-position: 'top-left'
      page-margins: 'standard'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'

  - type: RemovePages
    args:
      input-pdf-file: 'C:\Users\foo\AppData\Local\Temp\input.pdf'
      pages-to-remove: '1,3'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'

  - type: ConvertToGrayscale
    args:
      input-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'
      dpi: '200.0'
      output-page-size: 'LEGAL'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'

  - type: AddWatermark
    args:
      input-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'
      watermark-text : 'DUPLICATE'
      watermark-font-size: '40'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'

  - type: EncryptPdf
    args:
      input-pdf-file: 'C:\Users\foo\AppData\Local\Temp\intermediate.pdf'
      output-pdf-file: 'C:\Users\foo\AppData\Local\Temp\encrypted\output.pdf'

  - type: DecryptPdfs
    args:
      input-pdfs-directory: 'C:\Users\foo\AppData\Local\Temp\encrypted'
      output-pdfs-directory: 'C:\Users\foo\AppData\Local\Temp\decrypted'
----

Run the pipeline.

[source,cmd]
----
pdf-tools-%RELEASE_VERSION%\bin\pdf-tools.bat Pipeline^
    "C:\Users\foo\AppData\Local\Temp\pdf-transformation-pipeline.yaml"#<1>
----
<1> Command arguments - pipeline specification file

[discrete]
===== Linux
[source,sh]
----
cat <<EOF > /tmp/pdf-transformation-pipeline.yaml
transformations:
  - type: ImagesToPdf
    args:
      input-images-directory: '/tmp/images'
      output-page-size: 'A4'
      image-position: 'top-left'
      page-margins: 'standard'
      output-pdf-file: '/tmp/intermediate.pdf'

  - type: RemovePages
    args:
      input-pdf-file: '/tmp/input.pdf'
      pages-to-remove: '1,3'
      output-pdf-file: '/tmp/intermediate.pdf'

  - type: ConvertToGrayscale
    args:
      input-pdf-file: '/tmp/intermediate.pdf'
      dpi: '200.0'
      output-page-size: 'LEGAL'
      output-pdf-file: '/tmp/intermediate.pdf'

  - type: AddWatermark
    args:
      input-pdf-file: '/tmp/intermediate.pdf'
      watermark-text : 'DUPLICATE'
      watermark-font-size: '40'
      output-pdf-file: '/tmp/intermediate.pdf'

  - type: EncryptPdf
    args:
      input-pdf-file: '/tmp/intermediate.pdf'
      output-pdf-file: '/tmp/encrypted/output.pdf'

  - type: DecryptPdfs
    args:
      input-pdfs-directory: '/tmp/encrypted'
      output-pdfs-directory: '/tmp/decrypted'

EOF

pdf-tools-${RELEASE_VERSION}/bin/pdf-tools.sh Pipeline \
    "/tmp/pdf-transformation-pipeline.yaml"#<1>
----
<1> Command arguments - pipeline specification file

ifndef::hide-docker[]
[discrete]
==== Using Docker container
[source,sh]
----
cat <<EOF > /tmp/foo/pdf-transformation-pipeline.yaml
transformations:
  - type: ImagesToPdf
    args:
      input-images-directory: '/tmp/bar/images'
      output-page-size: 'A4'
      image-position: 'top-left'
      page-margins: 'standard'
      output-pdf-file: '/tmp/bar/intermediate.pdf'

  - type: RemovePages
    args:
      input-pdf-file: '/tmp/bar/input.pdf'
      pages-to-remove: '1,3'
      output-pdf-file: '/tmp/bar/intermediate.pdf'

  - type: ConvertToGrayscale
    args:
      input-pdf-file: '/tmp/bar/intermediate.pdf'
      dpi: '200.0'
      output-page-size: 'LEGAL'
      output-pdf-file: '/tmp/bar/intermediate.pdf'

  - type: AddWatermark
    args:
      input-pdf-file: '/tmp/bar/intermediate.pdf'
      watermark-text : 'DUPLICATE'
      watermark-font-size: '40'
      output-pdf-file: '/tmp/bar/intermediate.pdf'

  - type: EncryptPdf
    args:
      input-pdf-file: '/tmp/bar/intermediate.pdf'
      output-pdf-file: '/tmp/bar/output.pdf'

  - type: DecryptPdfs
    args:
      input-pdfs-directory: '/tmp/bar'
      output-pdfs-directory: '/tmp/baz'

EOF

docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools Pipeline \
    "/tmp/bar/pdf-transformation-pipeline.yaml"#<1>
----
<1> Command arguments - pipeline specification file
endif::[]
