= README
:experimental:
:icons: font
:revdate: 2023-04-02
:sectnums:
:sectnumlevels: 5
:toclevels: 5
:toc:

:blank: pass:[ +]


== Build
=== Build Windows executable
==== Prerequisites
. Install https://www.graalvm.org/[GraalVM] v22.3+.

. Install https://www.graalvm.org/22.3/reference-manual/native-image/[Native Image].
+
NOTE: On Windows, Native Image requires Visual Studio Code and Microsoft Visual C++(MSVC).

. Install https://maven.apache.org/[Apache Maven]

==== Build
. Open `Developer Command Prompt for VS 2022` in Windows Terminal.
+
.Developer Command Prompt for VS 2022
[source]
----
******************************************************
** Visual Studio 2022 Developer Command Prompt v17.5.3
** Copyright (c) 2022 Microsoft Corporation
******************************************************

>
----

. Run Maven build.
+
[source,cmd]
----
> cd <project-directory>

pdf-tools> set JAVA_HOME=<graalvm-home-directory>

pdf-tools> mvn -Pnative package
----


=== Build Docker image
==== Prerequisites
. Install https://docs.docker.com/[Docker].

. Start Docker Engine.
+
[source,cmd]
----
sudo service docker start
----

==== Build
. Run Maven build.
+
[source,cmd]
----
mvn -Pdocker verify
----


== Usage
=== Using Docker container
==== Encrypt PDF document
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    EncryptPdf \#<2>
    "/tmp/bar/kay.pdf" "/tmp/bar/encrypted-kay.pdf"#<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, output PDF file

==== Convert PDF pages to images
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    PdfToImage \#<2>
    "/tmp/bar/input.pdf" "/tmp/bar/" "1,2,3" 300 "jpeg" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, output directory, page numbers, DPI, image format.

==== Remove pages from PDF document
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    RemovePages \#<2>
    "/tmp/bar/input.pdf" "1,3" "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, page numbers to remove, output PDF file

==== Add watermark to PDF pages
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    AddWatermark \#<2>
    "/tmp/bar/input.pdf" "DUPLICATE" 40 "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, watermark text, font size, output PDF file

==== Convert PDF document to grayscale
[source,sh]
----
docker run -it \
    -v "/tmp/foo:/tmp/bar" \
    pdf-tools \#<1>
    ConvertToGrayscale \#<2>
    "/tmp/bar/input.pdf" 200 "LEGAL" "/tmp/bar/output.pdf" #<3>
----
<1> Container image name
<2> Command name
<3> Command arguments - input PDF file, image DPI, output page size, output PDF file
