name: Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify

      - name: Copy artifacts to staging
        run: mkdir staging && cp target/pdf-tools-0.1.0-linux.zip target/pdf-tools-0.1.0-windows.zip staging/ && cp target/sbom/cyclonedx.json staging/sbom-cyclonedx.json

      - name: Upload artifacts from staging
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging